server:
  port: 8080
spring:
  application:
    name: guide-1-mobile-engineering
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/guide1
    username: dbguide1
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
app:
  jwt:
    secret: DevManuel@1988!